# Configuration file for AppVeyor CI
configuration: Release

image:
- Visual Studio 2019

environment:
  matrix:
    - QTDIR: C:\Qt\5.12.6\mingw73_32
      CMAKE_GENERATOR: MinGW Makefiles
      MINGW_PATH: C:\Qt\Tools\mingw730_32

    - QTDIR: C:\Qt\5.12.6\msvc2017_64
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_GENERATOR_ARCH: x64
      CMD_VCVARS: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'
      BUILD_SUB_DIR: Debug

# Parameters for default build commands (build_script is used instead).
build:

install:
- utils\appveyor\install.bat

before_build:
- utils\appveyor\before_build.bat

build_script:
- utils\appveyor\build_script.bat

after_build:
- utils\appveyor\after_build.bat

artifacts:
- path: 'copyq*.zip'
  name: CopyQ Portable

- path: 'copyq-*-setup.exe'
  name: CopyQ Setup

# Upload test log files.
on_finish:
- ps: Get-ChildItem -recurse -include copyq*.log* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
